name: Build web app
description: Build the web app

inputs:
  web_app_location:
    required: true
    description: 'The location of the web app'
    
runs:
  using: composite  
  steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        shell: bash
        working-directory: ${{ inputs.web_app_location }}
        run: |
          npm ci

      - name: Build project
        shell: bash
        working-directory: ${{ inputs.web_app_location }}
        run: |
          npm run build
