name: Deploy azure function app
description: Deploy Azure function app to Azure

inputs:
  app_name:
    required: true
    description: 'The name of the function app'
  app_location:
    required: true
    description: 'The location of the function app'
  publish_profile:
    required: true
    description: 'The publish profile of the function app'


runs:
  using: composite  
  steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build and Deploy function app
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ inputs.app_name }}
          package: '${{ inputs.app_location }}'
          publish-profile: ${{ inputs.publish_profile }}
