name: Deploy azure function app
description: Deploy Azure function app to Azure

inputs:
  app_name:
    required: true
    description: 'The name of the function app'
  app_location:
    required: true
    description: 'The location of the function app'
  azure_credentials:
      description: 'The credentials to use to login to Azure'
      required: true
  app_artifact_name:
    required: true
    description: 'The name of the artifact to download'

runs:
  using: composite  
  steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.app_artifact_name }}
          path: ${{ inputs.app_location }}
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ inputs.azure_credentials }}
          
      - name: Build and Deploy function app
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ inputs.app_name }}
          package: '${{ inputs.app_location }}'
