name: Deploy web app
description: Deploy the infrastructure, web app and api to Azure

inputs:
  web_app_location:
    required: true
    description: 'The location of the web app'
  web_app_artifact_location:
    required: true
    description: 'The location of the web app artifact, relative to the web app location'
  azure_credentials:
      description: 'The credentials to use to login to Azure'
      required: true
  github_token:
      description: 'The token to use to login to GitHub'
      required: true
  deployment_token:
      description: 'The token to use to deploy the web app'
      required: true
    
runs:
  using: composite  
  steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ inputs.azure_credentials }}

      - name: Build and Deploy web app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ inputs.deployment_token }}
          repo_token: ${{ inputs.github_token }}
          action: "upload"
          app_location: ${{ inputs.web_app_location }}
          app_artifact_location: ${{ inputs.web_app_artifact_location }}
