name: Build and test CMS
run-name: Build and test CMS

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'cms/**'

env:
  DOTNET_APP_LOCATION: cms
  DOTNET_APP_NAME: Explore.Cms
  OUTPUT_LOCATION: ${{ github.workspace }}/outputs/cms

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build CMS
        uses: ./.github/actions/build-dotnet-app
        with:
          app_location: ${{ env.DOTNET_APP_LOCATION }}
          app_name: ${{ env.DOTNET_APP_NAME }}
          output_location: ${{ env.OUTPUT_LOCATION }}

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        uses: ./.github/actions/test-dotnet-app
        with:
          app_location: ${{ env.DOTNET_APP_LOCATION }}
