name: Build and deploy web app
run-name: Build and deploy web app

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'project/web/**'

env:
    WEB_APP_LOCATION: project/web
    WEB_APP_ARTIFACT_LOCATION: dist # relative to WEB_APP_LOCATION

jobs:
  build:
    name: Build web app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build web app
        uses: ./.github/actions/build-web-app
        with:
          web_app_location: ${{ env.WEB_APP_LOCATION }}

  deploy-dev:
    needs: [build]
    runs-on: ubuntu-latest
    environment: dev

    steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.azure_credentials }}

        - name: Build and Deploy web app
          uses: Azure/static-web-apps-deploy@v1
          env:
            VITE_AUTH_CLIENT_ID: ${{ secrets.VITE_AUTH_CLIENT_ID }}
          with:
            azure_static_web_apps_api_token: ${{ secrets.WEBAPP_DEPLOYMENT_TOKEN }}
            repo_token: ${{ secrets.github_token }}
            action: "upload"
            app_location: ${{ env.WEB_APP_LOCATION }}
            app_artifact_location: ${{ env.WEB_APP_ARTIFACT_LOCATION }}
