name: Build and test spa web
run-name: Build and test spa web

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'spa/web/**'
      - .github/workflows/build-and-test-webapp-spa.yaml
      - .github/actions/build-web-app/**

env:
  WEB_APP_LOCATION: spa/web
  WEB_APP_TEST_LOCATION: spa/test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        shell: bash
        working-directory: ${{ env.WEB_APP_LOCATION }}
        run: |
          npm ci

      - name: Build project
        shell: bash
        working-directory: ${{ env.WEB_APP_LOCATION }}
        run: |
          npm run build
        

  test:
      needs: build
      runs-on: ubuntu-latest
      environment: dev

      steps:
        - uses: actions/checkout@v3

        - name: Setup Node
          uses: actions/setup-node@v3
        
        - name: Install dependencies
          shell: bash
          working-directory: ${{ env.WEB_APP_TEST_LOCATION }}
          run: |
            npm ci

        - name: Install Playwright
          shell: bash
          working-directory: ${{ env.WEB_APP_TEST_LOCATION }}
          run: |
            npx playwright install --with-deps

        - name: Run tests
          working-directory: ${{ env.WEB_APP_TEST_LOCATION }}
          env:
            BASE_URL: ${{vars.BASE_URL_SPA }}
            API_BASE_URL: ${{ vars.API_BASE_URL_SPA }}
            LOGIN_URL: ${{ vars.LOGIN_URL_SPA }}
            LOGIN_USERNAME: ${{ secrets.TEST_LOGIN_USERNAME }}
            LOGIN_PASSWORD: ${{ secrets.TEST_LOGIN_PASSWORD }}
          run: npm run test
