name: Build and deploy excursion api
run-name: Build and deploy excursion api

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'excursion/api/**'

env:
    DOTNET_APP_LOCATION: excursion/api
    DOTNET_APP_NAME: Explore.Excursion
    OUTPUT_LOCATION: ${{ github.workspace }}/outputs/api

jobs:
  build:
    name: Build function app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build function app
        uses: ./.github/actions/build-dotnet-app
        with:
          app_location: ${{ env.DOTNET_APP_LOCATION }}
          app_name: ${{ env.DOTNET_APP_NAME }}
          output_location: ${{ env.OUTPUT_LOCATION }}

  deploy-dev:
    needs: [build]
    runs-on: ubuntu-latest
    environment: dev

    steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Deploy function app
          uses: ./.github/actions/deploy-azure-function-app
          with:
              app_location: ${{ env.OUTPUT_LOCATION }}
              app_artifact_name: ${{ env.DOTNET_APP_NAME }}
              app_name: ${{ vars.API_FUNCTION_APP_NAME_EXCURSION }}
              azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
