name: Validate infrastructure

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  INFRASTRUCTURE_TEMPLATE_LOCATION: ./infrastructure/main.bicep
  INFRASTRUCTURE_PARAMETER_LOCATION: ./infrastructure/parameters/common.json
  WEB_APP_LOCATION: project/web
  WEB_APP_ARTIFACT_LOCATION: dist # relative to WEB_APP_LOCATION

jobs:
 validate-infrastructure:
    environment: dev

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate infrastructure
        uses: ./.github/actions/infrastructure
        with:
          deploy: false
          resource_group: ${{ secrets.AZURE_RG }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION }}
          parameter_file: ${{ env.INFRASTRUCTURE_PARAMETER_LOCATION }}
          environment: dev
          template_file: ${{ env.INFRASTRUCTURE_TEMPLATE_LOCATION }}
